### ISSUE TITLE
save

### ISSUE THREAD

**Issue by dinobossytnew** [ACM02/XpBank#4]
is posiblee add:
save.yml or jason or support mysql for evitation errors or bugs.

**Comment by ACM02** [comment]
That is a feature I have wanted to implement for a while but never got around to. I'll likely have time at the end of this month to take a look at it and it seems like a fun challenge so I hope I can get around to it!

**Comment by ACM02** [comment]
Good news! It looks like this was a pretty quick thing to implement.
Check out the new version (1.12.6) of the plugin to see the changes!
If what I've implemented wasn't what you were imagining/isn't what you were wanting please let me know.
